"""simulateimu.py -- the simulated IMU (gyroscope + magnetometer), all in one file.

WHAT THIS IS (plain language): a stand-in for the real gyroscope and
magnetometer chips the satellite will carry. A gyroscope does NOT measure
attitude -- it measures HOW FAST the spacecraft is spinning (body angular
rate, rad/s). A magnetometer does NOT measure attitude either -- it measures
the EARTH'S MAGNETIC FIELD as seen from the spacecraft's own body frame
(Tesla, this repo's convention). A separate program (an attitude estimator /
filter) later combines these two with the sun vector to deduce attitude. This
file only simulates the two SENSORS right.

Every measurement is slightly wrong in the same ways a real chip is wrong:
scale factor, axis misalignment, a constant startup bias, a slowly-drifting
bias (wander), fresh white noise, tiny latency, occasional dropouts and, for
the magnetometer, a fixed "hard-iron" offset and a spacecraft-generated
magnetic disturbance.

CONFIGURE (the ONE line, in satellite_parameters.py):
    IMU_SIM = ImuSimParameters.nominal()    # realistic (default)
    IMU_SIM = ImuSimParameters.off()        # behave exactly like before IMU
    IMU_SIM = ImuSimParameters.perfect()    # zero error (plumbing check)
    IMU_SIM = ImuSimParameters.degraded()   # worse but plausible
    IMU_SIM = ImuSimParameters.stress()     # very poor (robustness testing)

SELF-TEST (from the project root):
    python simulateimu.py               # 120 s demo, prints statistics
    python simulateimu.py validate      # full proof (10 sensor stages)

PLAIN-LANGUAGE GLOSSARY:
    bias          a sensor error that starts at some offset and persists.
    wander        a slowly changing error that REMEMBERS its previous value
                  (Gauss-Markov process; tau = seconds until it forgets).
    white         fresh random noise with no memory, redrawn every sample.
    scale         the sensor reports slightly too large or too small.
    misalignment  one sensor axis slightly leaks into another.
    hard-iron     fixed magnetic offset caused by the spacecraft's own
                  electronics and materials (permanent magnets in effect).
    disturbance   extra magnetic field GENERATED BY THE SPACECRAFT itself.
    saturation    the sensor cannot report beyond its physical range.
    latency       the measurement describes the state a few ms in the past.
    dropout       a sample where the sensor reports nothing (invalid).

UNITS: body angular rate in radians/second (rad/s, the repo's live state
unit) and magnetic field in TESLA (T, the repo's live B_eci unit from
engine_adcs_bridge). The real hardware datasheets quote deg/s and nT; the
config comments give those numbers too (the dashboard shows nanotesla,
because 1e-8 T is unreadable).

GOLDEN RULES (enforced below):
    1. This module NEVER advances or fetches the simulation truth. Truth
       (attitude quaternion, body rate, magnetic field) is passed IN by the
       simulation loop each tick -- the sensor is a pure "lying machine":
       truth in -> sensor errors -> measurement out.
    2. ALL randomness comes from ONE numpy generator seeded from
       ImuSimParameters.seed. No global np.random anywhere.
    3. No hand-rolled physics beyond the repo's OWN quaternion convention
       (B_body = C_bi.T @ B_eci, the exact formula used everywhere in this
       project) -- see _dcm_bi_from_q.
    4. Measured values are what the simulated flight electronics consume.
       Truth is kept separately (in the in-memory records) for validation only.
"""
from __future__ import annotations

import collections
import math
import sys
from dataclasses import dataclass, replace

import numpy as np

from simulatesunsensor import SimulatedSunSensorArray

def _dcm_bi_from_q(q):
    """Attitude matrix dcm body->ECI (v_eci = C_bi @ v_body) from a
    scalar-first [q0, q1, q2, q3] quaternion -- copied EXACTLY from
    satellite_rotational_dynamics_var_mag_field.py (and the identical formula
    in calculate_disturbances._dcm_bi_from_q and satellite_flight_visualisation.py).
    The repo's load-bearing convention for body-frame vectors is:
        B_body = C_bi.T @ B_eci
    using this same matrix. Do NOT "fix" this formula -- it IS the repo.
    """
    q = np.asarray(q, dtype=float).reshape(4)
    q = q / np.linalg.norm(q)
    q0, q1, q2, q3 = q
    return np.array([
        [1 - 2 * (q2**2 + q3**2),     2 * (q1 * q2 + q0 * q3),     2 * (q1 * q3 - q0 * q2)],
        [2 * (q1 * q2 - q0 * q3),     1 - 2 * (q1**2 + q3**2),     2 * (q2 * q3 + q0 * q1)],
        [2 * (q1 * q3 + q0 * q2),     2 * (q2 * q3 - q0 * q1),     1 - 2 * (q1**2 + q2**2)],
    ])


def white_noise(rng, sigma: float) -> float:
    """One fresh, memoryless random draw of size `sigma` (zero on average)."""
    if sigma < 0.0:
        raise ValueError("white-noise sigma must be >= 0")
    return sigma * rng.standard_normal()


class GaussMarkov:
    """One axis of a slowly-wandering error (wants: sigma >= 0, tau > 0).

    Advance rule (exact for a discrete step of any size):
        b_new = exp(-dt/tau) * b + sqrt(1 - exp(-2*dt/tau)) * sigma * N(0,1)
    With dt = 0 the state is left unchanged, so the very first call is safe.
    (Same small class as simulategps.py's GaussMarkov, kept self-contained so
    this file stands alone like simulategps.py does.)
    """

    __slots__ = ("sigma", "tau", "_value")

    def __init__(self, sigma: float, tau: float, initial: float = 0.0) -> None:
        if sigma < 0.0:
            raise ValueError("GaussMarkov sigma must be >= 0")
        if tau <= 0.0:
            raise ValueError("GaussMarkov tau must be > 0")
        self.sigma = float(sigma)
        self.tau = float(tau)
        self._value = float(initial)

    @property
    def value(self) -> float:
        return self._value

    def advance(self, dt_seconds: float, rng) -> None:
        """Move the wander forward by dt_seconds of simulated time."""
        dt = float(dt_seconds)
        if dt <= 0.0:
            return
        decay = float(np.exp(-dt / self.tau))
        self._value = (decay * self._value
                       + float(np.sqrt(1.0 - decay * decay)) * self.sigma * rng.standard_normal())

    def reset(self) -> None:
        self._value = 0.0

# ---------------------------------------------------------------------------
# Measurement dataclasses -- one output of each sensor, units/frames explicit.
# ---------------------------------------------------------------------------
@dataclass
class GyroMeasurement:
    """One gyro sample. Units: radians/second, BODY frame, order [X, Y, Z].
    t_meas_s  = sim time the motion DESCRIBED; t_arrival_s = when it arrived
    (t_arrival_s >= t_meas_s when latency is enabled)."""
    t_meas_s: float
    t_arrival_s: float
    omega_body_rad_s: np.ndarray          # measured body rate [X, Y, Z] (rad/s)
    bias_rad_s: np.ndarray                # bias applied (constant + wander) [rad/s]
    wander_rad_s: np.ndarray              # only the wander part [rad/s]
    white_noise_rad_s: np.ndarray         # fresh noise that sample [rad/s]
    saturated: bool                       # clipped to the measurement range?
    valid: bool                           # False on a dropout sample


@dataclass
class MagnetometerMeasurement:
    """One magnetometer sample. Units: TESLA, BODY frame, order [X, Y, Z].
    This repo's live convention for the body field is Tesla (B_eci from
    engine_adcs_bridge is Tesla); the real hardware datasheet quotes nT
    (1e-9 T) -- see the module docstring / README for both."""
    t_meas_s: float
    t_arrival_s: float
    magnetic_field_body_t: np.ndarray     # measured body field [X, Y, Z] (T)
    hard_iron_bias_t: np.ndarray          # fixed spacecraft-hull offset applied [T]
    disturbance_body_t: np.ndarray        # spacecraft-generated field applied [T]
    white_noise_t: np.ndarray             # fresh noise that sample [T]
    saturated: bool                       # clipped to the measurement range?
    valid: bool                           # False on a dropout sample


class SimulatedIMU:
    """The simulated IMU (gyroscope + magnetometer + coarse-sun-sensor array).
    Feed the TRUE state each loop tick with
    update(t, q_truth, omega_truth, B_eci_truth, sun_eci_truth,
    eclipse_fraction, position_eci); it answers with
    (GyroMeasurement|None, MagnetometerMeasurement|None,
    SunArrayMeasurement|None) on each sensor's own schedule (None = that
    sensor did not tick this update). The sun array (simulatesunsensor.py)
    is OWNED here when enable_sun_sensor is set and runs on its own grid.

    It NEVER touches the simulation truth itself -- truth comes in as
    arguments (the "lying machine" rule).
    """

    def __init__(self, config, epoch_utc=None, record_history=True) -> None:
        self.cfg = config
        self._gyro_mount = _dcm_bi_from_q(config.gyro_mount_quaternion)
        self._mag_mount = _dcm_bi_from_q(config.mag_mount_quaternion)
        self.epoch_utc = epoch_utc                # never used for state
        self.rng = np.random.default_rng(config.seed)      # ONE generator, all randomness

        # ---- gyroscope calibration: scale + axis misalignment matrix --------
        self._M_gyro = self._build_calibration_matrix(
            config.gyro_scale_error, config.gyro_misalignment_rad)
        if config.gyro_bias_sigma_rad_s > 0.0:
            self._gyro_bias_const = np.array([
                white_noise(self.rng, config.gyro_bias_sigma_rad_s) for _ in range(3)])
        else:
            self._gyro_bias_const = np.zeros(3)
        self._gyro_wander = ([GaussMarkov(config.gyro_wander_sigma_rad_s, config.gyro_wander_tau_s)
                              for _ in range(3)]
                             if config.gyro_wander_sigma_rad_s > 0.0 else None)

        # ---- magnetometer calibration + hard-iron + spacecraft disturbance --
        self._M_mag = self._build_calibration_matrix(
            config.mag_scale_error, config.mag_misalignment_rad)
        if config.mag_hard_iron_bias_sigma_t > 0.0:
            self._mag_hard_iron = np.array([
                white_noise(self.rng, config.mag_hard_iron_bias_sigma_t) for _ in range(3)])
        else:
            self._mag_hard_iron = np.zeros(3)
        self._mag_disturb_fixed = np.asarray(config.mag_disturbance_t, dtype=float).reshape(3)
        self._mag_disturb_wander = ([
            GaussMarkov(config.mag_disturbance_wander_sigma_t,
                        config.mag_disturbance_wander_tau_s) for _ in range(3)]
            if config.mag_disturbance_wander_sigma_t > 0.0 else None)

        # ---- scheduling / bookkeeping ---------------------------------------
        self._last_t = None
        self._gyro_last_k = -1
        self._mag_last_k = -1
        # ---- the coarse-sun-sensor ARRAY (simulatesunsensor.py) -------------
        # The IMU owns the array when the sun sensor is enabled; it keeps its
        # OWN grid, truth history and validation records.
        self._sun_array = (SimulatedSunSensorArray(config.sun_array, record_history=record_history)
                           if config.enable_sun_sensor and config.sun_array.enabled else None)
        # truth history (t, q, omega, B_eci); 50 samples ~ 5 s at 0.1 s ticks,
        # far more than the largest configured latency (0.25 s in stress).
        self._history = collections.deque(maxlen=50)
        self.gyro_samples = 0                  # gyro grid outputs (valid + dropout)
        self.mag_samples = 0                   # mag grid outputs (valid + dropout)
        self.sun_samples = 0                   # sun-sensor grid outputs
        self._last_gyro_rec = None             # most recent gyro record (validation)
        self._last_mag_rec = None              # most recent mag record (validation)

        # ---- logging ---------------------------------------------------------
        self.records = [] if record_history else collections.deque(maxlen=2)
        self._units = {}
        for kind, group in (('gyro', config.gyros), ('mag', config.magnetometers)):
            if group:
                self._units[kind] = [(unit, SimulatedIMU(config.unit_config(kind, unit, i),
                                      record_history=record_history))
                                     for i, unit in enumerate(group) if unit.enabled]
        self._M_gyro = np.asarray(config.gyro_response_matrix) @ self._M_gyro
        self._M_mag = np.asarray(config.mag_response_matrix) @ self._M_mag
        self._gyro_bias_const += np.asarray(config.gyro_fixed_bias_rad_s)
        self._mag_hard_iron += np.asarray(config.mag_fixed_bias_t)

    def _build_calibration_matrix(self, scale_error: float, misalignment_rad: float):
        """Scale-factor + axis-misalignment matrix M (applied to the true
        vector, e.g. omega_meas = M @ omega_true).

        M = diag(1+sx, 1+sy, 1+sz) + small off-diagonal misalignment terms,
        each drawn once at power-on from N(0, misalignment_rad). Real sensors
        have this because the chip axes are not perfectly aligned to the
        spacecraft axes and the scale can be slightly off. Drawn from this
        IMU's own rng so it is deterministic for a given seed.
        """
        scale = 1.0 + np.array([white_noise(self.rng, scale_error) if scale_error > 0 else 0.0
                                for _ in range(3)])
        M = np.diag(scale)
        if misalignment_rad > 0.0:
            M[0, 1] = white_noise(self.rng, misalignment_rad)
            M[0, 2] = white_noise(self.rng, misalignment_rad)
            M[1, 0] = white_noise(self.rng, misalignment_rad)
            M[1, 2] = white_noise(self.rng, misalignment_rad)
            M[2, 0] = white_noise(self.rng, misalignment_rad)
            M[2, 1] = white_noise(self.rng, misalignment_rad)
        return M

# ---- internal helpers ----------------------------------------------------
    def _sample_truth_at(self, t_meas_s):
        """Linear interpolation of the buffered truth (t, q, omega, B_eci) at a
        slightly-past moment (latency). q is linearly interpolated component-
        wise then renormalized (fine over millisecond lags); the attitude
        changes negligibly over 0.001-0.25 s."""
        times = [h[0] for h in self._history]
        if t_meas_s <= times[0] or len(times) < 2:
            t0, q0, o0, b0 = self._history[0]
            return t0, q0, o0, b0
        from bisect import bisect_right
        j = bisect_right(times, t_meas_s) - 1
        j = min(max(j, 0), len(times) - 2)
        t0, q0, o0, b0 = self._history[j]
        t1, q1, o1, b1 = self._history[j + 1]
        if np.dot(q0, q1) < 0:
            q1 = -q1
        w = (t_meas_s - t0) / (t1 - t0) if t1 > t0 else 0.0
        q = q0 + w * (q1 - q0)
        q /= np.linalg.norm(q)
        return (t_meas_s, q, o0 + w * (o1 - o0), b0 + w * (b1 - b0))

    @staticmethod
    def _latency_draw(rng, mean, sigma, lo, hi):
        """One random latency value, clipped into [lo, hi] (chips have bounds)."""
        return float(np.clip(rng.normal(mean, sigma), lo, hi))

    # ---- the heartbeat -------------------------------------------------------
    def update(self, t_seconds, q_truth, omega_truth, B_eci_truth,
               sun_eci_truth=None, eclipse_fraction=1.0, position_eci=None):
        """Feed ONE loop tick of TRUE state. Returns
        (gyro, mag, sun) where each is a Measurement or None (that sensor did
        not tick this update) and a returned measurement with valid=False
        means a dropped (invalid) sample.

        Truth is passed IN: q_truth = scalar-first body->ECI quaternion,
        omega_truth = true body rate (rad/s), B_eci_truth = true Earth field
        in ECI (Tesla, the repo's engine_bridge convention), sun_eci_truth =
        true unit Sun direction in ECI (from the GPS clock; None leaves the
        sun array silent), eclipse_fraction = the engine lighting ratio in
        [0, 1] (the sun array's penumbra channel), position_eci = true ECI
        position (the sun array's Earth-albedo channel; None disables it).
        """
        cfg = self.cfg
        t = float(t_seconds)
        q = np.asarray(q_truth, dtype=float).reshape(4)
        omega = np.asarray(omega_truth, dtype=float).reshape(3)
        B_eci = np.asarray(B_eci_truth, dtype=float).reshape(3)

        if self._last_t is not None and t <= self._last_t:
            raise ValueError(
                f"SimulatedIMU.update received t={t} but the previous call was "
                f"t={self._last_t}. Time must move forward.")

        dt = 0.0 if self._last_t is None else t - self._last_t
        self._last_t = t
        self._history.append((t, q.copy(), omega.copy(), B_eci.copy()))

        # advance the slowly-wandering states by this tick's duration
        if self._gyro_wander is not None:
            for gm in self._gyro_wander:
                gm.advance(dt, self.rng)
        if self._mag_disturb_wander is not None:
            for gm in self._mag_disturb_wander:
                gm.advance(dt, self.rng)

        gyro = self._produce_gyro(t) if cfg.enable_gyro and not cfg.gyros else None
        mag = self._produce_mag(t) if cfg.enable_magnetometer and not cfg.magnetometers else None
        for kind, enabled in (('gyro', cfg.enable_gyro), ('mag', cfg.enable_magnetometer)):
            if kind in self._units:
                receipts = []
                if enabled:
                    for unit, hardware in self._units[kind]:
                        g, m, _ = hardware.update(t, q, omega, B_eci)
                        receipt = g if kind == 'gyro' else m
                        receipts.append((unit, receipt))
                if kind == 'gyro':
                    gyro = receipts
                else:
                    mag = receipts
        # The sun array runs on its OWN grid with its OWN truth history: hand
        # it this tick's truth (None sun direction = array stays silent). The
        # returned receipt is a SunArrayMeasurement (or None off-grid).
        sun = None
        if self._sun_array is not None and sun_eci_truth is not None:
            sun = self._sun_array.update(t, q, sun_eci_truth, eclipse_fraction,
                                         position_eci)
            if sun is not None:
                self.sun_samples += 1
        return gyro, mag, sun

    def _on_grid(self, t, period, last_k):
        """1 Hz-style grid check for one sensor: returns (k, t_grid) on a new
        boundary, else None. The boundary is consumed even on dropout so a
        dropped sample is never retried."""
        k = math.floor(t / period + 1e-9)
        if k <= last_k:
            return None
        return k, k * period

    def _produce_gyro(self, t):
        """Build one gyro sample on the gyro's own grid (None off-grid)."""
        cfg = self.cfg
        period = 1.0 / cfg.gyro_update_rate_hz
        grid = self._on_grid(t, period, self._gyro_last_k)
        if grid is None:
            return None
        k, t_grid = grid
        self._gyro_last_k = k
        self.gyro_samples += 1

        # latency: the sample describes the motion a few ms ago
        tau = self._latency_draw(self.rng, cfg.gyro_latency_mean_s,
                                 cfg.gyro_latency_sigma_s,
                                 cfg.gyro_latency_min_s, cfg.gyro_latency_max_s)
        t_meas, _, omega_true, _ = self._sample_truth_at(t_grid - tau)

        wander = (np.array([gm.value for gm in self._gyro_wander])
                  if self._gyro_wander is not None else np.zeros(3))
        bias = self._gyro_bias_const + wander
        noise = np.array([white_noise(self.rng, cfg.gyro_white_noise_sigma_rad_s)
                          for _ in range(3)])
        raw = self._M_gyro @ (self._gyro_mount.T @ omega_true) + bias + noise
        saturated = bool(np.any(np.abs(raw) > cfg.gyro_range_rad_s))
        omega_meas = np.clip(raw, -cfg.gyro_range_rad_s, cfg.gyro_range_rad_s)
        if cfg.gyro_quantization_rad_s > 0.0:
            omega_meas = np.round(omega_meas / cfg.gyro_quantization_rad_s) * cfg.gyro_quantization_rad_s
        valid = not (cfg.gyro_dropout_probability > 0.0
                     and self.rng.random() < cfg.gyro_dropout_probability)

        omega_meas = self._gyro_mount @ omega_meas
        meas = GyroMeasurement(
            t_meas_s=t_meas, t_arrival_s=t_grid, omega_body_rad_s=omega_meas,
            bias_rad_s=bias, wander_rad_s=wander, white_noise_rad_s=noise,
            saturated=saturated, valid=valid)
        self._last_gyro_rec = {
            "t_meas": t_meas, "t_arrival": t_grid,
            "truth": np.asarray(omega_true), "meas": np.asarray(omega_meas),
            "bias": np.asarray(bias), "wander": np.asarray(wander),
            "noise": np.asarray(noise), "valid": valid, "saturated": saturated}
        self.records.append(("gyro", self._last_gyro_rec))
        return meas

    def _produce_mag(self, t):
        """Build one magnetometer sample on the magnetometer's own grid."""
        cfg = self.cfg
        period = 1.0 / cfg.mag_update_rate_hz
        grid = self._on_grid(t, period, self._mag_last_k)
        if grid is None:
            return None
        k, t_grid = grid
        self._mag_last_k = k
        self.mag_samples += 1

        tau = self._latency_draw(self.rng, cfg.mag_latency_mean_s,
                                 cfg.mag_latency_sigma_s,
                                 cfg.mag_latency_min_s, cfg.mag_latency_max_s)
        t_meas, q_meas, _, B_eci_meas = self._sample_truth_at(t_grid - tau)

        # TRUE field in the body frame, using the repo's own convention:
        #     B_body = C_bi.T @ B_eci   (C_bi = body->ECI from the quaternion)
        B_true_body = _dcm_bi_from_q(q_meas).T @ B_eci_meas

        disturbance = (np.array([gm.value for gm in self._mag_disturb_wander])
                       if self._mag_disturb_wander is not None else np.zeros(3))
        disturbance = disturbance + self._mag_disturb_fixed
        noise = np.array([white_noise(self.rng, cfg.mag_white_noise_sigma_t)
                          for _ in range(3)])
        local_field = B_true_body + np.asarray(cfg.mag_gradient_body_t_per_m) @ np.asarray(cfg.mag_position_body_m)
        raw = (self._M_mag @ (self._mag_mount.T @ (local_field + disturbance))
               + self._mag_hard_iron + noise)
        saturated = bool(np.any(np.abs(raw) > cfg.mag_range_t))
        B_meas = np.clip(raw, -cfg.mag_range_t, cfg.mag_range_t)
        if cfg.mag_quantization_t > 0.0:
            B_meas = np.round(B_meas / cfg.mag_quantization_t) * cfg.mag_quantization_t
        valid = not (cfg.mag_dropout_probability > 0.0
                     and self.rng.random() < cfg.mag_dropout_probability)

        B_meas = self._mag_mount @ B_meas
        meas = MagnetometerMeasurement(
            t_meas_s=t_meas, t_arrival_s=t_grid, magnetic_field_body_t=B_meas,
            hard_iron_bias_t=self._mag_hard_iron, disturbance_body_t=disturbance,
            white_noise_t=noise, saturated=saturated, valid=valid)
        self._last_mag_rec = {
            "t_meas": t_meas, "t_arrival": t_grid,
            "truth": np.asarray(B_true_body), "meas": np.asarray(B_meas),
            "hard_iron": np.asarray(self._mag_hard_iron),
            "disturbance": np.asarray(disturbance), "noise": np.asarray(noise),
            "valid": valid, "saturated": saturated}
        self.records.append(("mag", self._last_mag_rec))
        return meas

# ---------------------------------------------------------------------------
# Shared: load the real truth sources the demo/validation use.
# ---------------------------------------------------------------------------
_TUMBLE_DEG_S_1 = 5.0      # representative tumble for exercising the sensors
_TUMBLE_DEG_S_2 = 3.0      # (the project's own C-firmware tests use the same
_TUMBLE_DEG_S_3 = -2.0     #  magnitude; the nominal y0 is zero rate which
                           #  would leave the attitude frozen -- boring)


def _real_truth_driver(provider, dt=0.1, t_end=120.0):
    """Generator of REAL truth for the demo/validation, using the repository's
    OWN physics core:

      * ATTITUDE + BODY RATE: torque-free rigid-body dynamics -- the exact same
        equations as rotational_equations_of_motion's physical core
        (I·w_dot = -w × I·w, q_dot = 0.5·Omega(q)·q) with the repo's own
        inertia (satellite_params) and a representative tumble, integrated at
        the loop step. A USE_TUMBLE=0 flag would reproduce the repo's current
        zero-rate y0.
      * MAGNETIC FIELD: the REAL IGRF B_eci from engine_adcs_bridge at the
        REAL engine-propagated orbit position.

    Yields (t, q_truth, omega_truth, B_eci_truth) each step.
    """
    import satellite_params as sp
    I = np.diag([sp.sat_Ixx, sp.sat_Iyy, sp.sat_Izz])
    I_inv = np.linalg.inv(I)
    q = np.array([1.0, 0.0, 0.0, 0.0])
    omega = np.radians([_TUMBLE_DEG_S_1, _TUMBLE_DEG_S_2, _TUMBLE_DEG_S_3])
    for i in range(1, int(round(t_end / dt)) + 1):
        t = i * dt
        r_vec, v_vec = provider.state_at(t)
        B_eci = provider.magnetic_field_eci(t, r_vec)
        # one step of the repo's own torque-free dynamics core
        w_dot = I_inv @ (-np.cross(omega, I @ omega))
        wx, wy, wz = omega
        Omega = np.array([[0, -wx, -wy, -wz],
                          [wx, 0, wz, -wy],
                          [wy, -wz, 0, wx],
                          [wz, wy, -wx, 0]])
        q = q + 0.5 * dt * (Omega @ q)
        q /= np.linalg.norm(q)
        omega = omega + dt * w_dot
        yield t, q, omega, B_eci


def _load_provider():
    import engine.orekit_runtime  # noqa: F401  side-effect JVM bootstrap
    from engine.orekit_runtime import ensure_initialized
    ensure_initialized()
    import satellite_parameters as config
    from engine_adcs_bridge import EngineOrbitProvider
    return EngineOrbitProvider(epoch_utc=config.EPOCH_UTC)


def run_demo() -> None:
    """A short standalone tour: 120 s on the real orbit + real IGRF field
    with the repo's own attitude dynamics, feeding the NOMINAL IMU. Prints
    measured-vs-truth statistics for both sensors.
    """
    import time
    print("=" * 78)
    print(" IMU SIMULATOR DEMO -- 120 s, NOMINAL profile (realistic errors)")
    print("=" * 78)

    provider = _load_provider()
    import satellite_parameters as config
    from sun_vector_eci import sun_vector_eci
    from datetime import timedelta
    imu = SimulatedIMU(config.IMU_SIM)

    t0 = time.perf_counter()
    for t, q, omega, B_eci in _real_truth_driver(provider, dt=0.1, t_end=120.0):
        # the Sun's ECI direction is known from the GPS clock (CLAUDE.md §5)
        sun = sun_vector_eci(config.EPOCH_UTC + timedelta(seconds=t))
        imu.update(t, q, omega, B_eci, sun)
    wall = time.perf_counter() - t0

    print(f"flew 120 s in {wall:.1f} s wall clock; "
          f"{imu.gyro_samples} gyro, {imu.mag_samples} mag, "
          f"{imu.sun_samples} sun-sensor outputs")
    print(f"  gyro outputs / valid : {imu.gyro_samples} / "
          f"{sum(1 for kind, r in imu.records if kind == 'gyro' and r['valid'])}")
    print(f"  mag  outputs / valid : {imu.mag_samples} / "
          f"{sum(1 for kind, r in imu.records if kind == 'mag' and r['valid'])}")
    if imu._sun_array is not None:
        srecs = imu._sun_array.records
        print(f"  sun  outputs / valid : {imu.sun_samples} / "
              f"{sum(1 for r in srecs if r['valid'])} "
              f"({sum(1 for r in srecs if r['reconstruction_valid'])} reconstructions solved)")

    ge = np.array([r["meas"] - r["truth"] for kind, r in imu.records if kind == "gyro" and r["valid"]])
    me = np.array([r["meas"] - r["truth"] for kind, r in imu.records if kind == "mag" and r["valid"]])
    if len(ge):
        print("\nsummary statistics (NOMINAL profile):")
        print(f"  gyro error std  X/Y/Z : "
              f"{np.degrees(ge[:, 0].std()):.4f} / {np.degrees(ge[:, 1].std()):.4f} / "
              f"{np.degrees(ge[:, 2].std()):.4f} deg/s")
        print(f"  gyro error mean X/Y/Z : "
              f"{np.degrees(ge[:, 0].mean()):+.4f} / {np.degrees(ge[:, 1].mean()):+.4f} / "
              f"{np.degrees(ge[:, 2].mean()):+.4f} deg/s")
    if len(me):
        print(f"  mag error std  X/Y/Z : "
              f"{me[:, 0].std() * 1e9:.1f} / {me[:, 1].std() * 1e9:.1f} / "
              f"{me[:, 2].std() * 1e9:.1f} nT")
        print(f"  mag error mean X/Y/Z : "
              f"{me[:, 0].mean() * 1e9:+.1f} / {me[:, 1].mean() * 1e9:+.1f} / "
              f"{me[:, 2].mean() * 1e9:+.1f} nT")
    if imu._sun_array is not None:
        good = [r for r in imu._sun_array.records if r["reconstruction_valid"]]
        if good:
            angs = np.array([np.degrees(np.arccos(np.clip(
                float(np.dot(r["meas"], r["truth"])), -1.0, 1.0))) for r in good])
            print(f"  sun recon error mean/std : {angs.mean():.3f} / {angs.std():.3f} deg "
                  f"({len(good)}/{len(imu._sun_array.records)} receipts solved)")
    print("\ndone.")

# --- validation harness ------------------------------------------------------
_VAL_RESULTS = []                 # (stage, name, ok, detail)
_VAL_DT = 0.1


def _check(stage: str, name: str, ok: bool, detail: str) -> None:
    _VAL_RESULTS.append((stage, name, bool(ok), detail))
    print(f"  [{'PASS' if ok else 'FAIL'}] {stage:<10} {name}: {detail}", flush=True)


def _synthetic_gyro_loop(imu, duration_s=600.0, omega=None, dt=None):
    """Feed a CONSTANT synthetic truth so statistical checks measure ONLY the
    sensor model: q = identity, omega = fixed body rate (rad/s), B_eci = a
    fixed vector, sun_eci = a fixed second reference. Returns the sensor
    records at the end."""
    dt = dt if dt is not None else _VAL_DT
    omega = np.array([0.3, -0.15, 0.05]) if omega is None else np.asarray(omega, float)
    q_ident = np.array([1.0, 0.0, 0.0, 0.0])
    # B_eci chosen so B_body is a nice non-trivial vector via the repo's C_bi.T;
    # sun_eci is NOT parallel to B_eci (real attitude determination needs two
    # non-parallel references -- exactly the point of adding the sun sensor).
    B_eci = np.array([2.0e-5, 1.0e-5, 1.5e-5])
    # sun chosen so >=3 array cells are lit well inside their FOV cones (the
    # onboard least-squares reconstruction needs >=3 non-coplanar cells)
    sun_eci = np.array([1.0, 1.0, 1.0]); sun_eci /= np.linalg.norm(sun_eci)
    for i in range(1, int(round(duration_s / dt)) + 1):
        imu.update(i * dt, q_ident, omega, B_eci, sun_eci)
    return imu


def _finalize(cfg_factory, seed=42, duration=600.0):
    from satellite_parameters import ImuSimParameters
    cfg = cfg_factory()
    cfg = replace(cfg, seed=seed)
    imu = SimulatedIMU(cfg)
    _synthetic_gyro_loop(imu, duration_s=duration)
    return imu


# ---- STAGE 1: PERFECT ------------------------------------------------------
def _check_perfect() -> None:
    from satellite_parameters import ImuSimParameters
    imu = _finalize(ImuSimParameters.perfect)
    grecs = [r for k, r in imu.records if k == "gyro"]
    mrecs = [r for k, r in imu.records if k == "mag"]
    if not grecs or not mrecs:
        _check("PERFECT", "samples exist", False, "no gyro/mag records")
        return
    # (1) gyro measurement == true body rate (units/frame/order), max abs err
    ge = np.array([r["meas"] - r["truth"] for r in grecs])
    gmax = float(np.max(np.abs(ge)))
    _check("PERFECT", "1 gyro == truth", gmax < 1e-12,
           f"max |meas-truth| = {gmax:.3e} rad/s (< 1e-12)  [axis order X,Y,Z]")
    # (2) mag measurement == true body field (Tesla)
    me = np.array([r["meas"] - r["truth"] for r in mrecs])
    mmax = float(np.max(np.abs(me)))
    _check("PERFECT", "2 mag == truth", mmax < 1e-12,
           f"max |meas-truth| = {mmax:.3e} T (< 1e-12)  [X,Y,Z, Tesla]")
    # (2b) sun ARRAY reconstruction == true body unit direction (dimensionless)
    if imu._sun_array is not None:
        srecs = imu._sun_array.records
        good = [r for r in srecs if r["reconstruction_valid"]]
        se = (np.array([r["meas"] - r["truth"] for r in good])
              if good else np.zeros((0, 3)))
        smax = float(np.max(np.abs(se))) if len(good) else float("inf")
        _check("PERFECT", "2b sun recon == truth",
               len(srecs) > 0 and len(good) == len(srecs) and smax < 1e-9,
               f"max |recon-truth| = {smax:.3e} (< 1e-9), "
               f"{len(good)}/{len(srecs)} receipts solved")
    else:
        _check("PERFECT", "2b sun recon == truth", False, "no sun array owned")
    # (3) cadence: exactly one gyro sample per 0.1 s tick, evenly spaced
    ts = np.array([r["t_arrival"] for r in grecs])
    gaps = np.diff(ts)
    _check("PERFECT", "3 cadence", np.all(np.abs(gaps - _VAL_DT) < 1e-9),
           f"{len(ts)} samples, gaps {'all exactly 0.1 s' if len(ts) else 'none'}")
    # (4) timestamps: arrival >= meas (latency) always
    ok_lag = all(r["t_arrival"] >= r["t_meas"] - 1e-12 for r in grecs + mrecs)
    _check("PERFECT", "4 timestamps", ok_lag,
           "t_arrival >= t_meas for every sample")
    # (5) no dropouts / no saturation in perfect mode
    ok_flags = all(r["valid"] and not r["saturated"] for r in grecs + mrecs)
    _check("PERFECT", "5 flags clean", ok_flags,
           "all valid, none saturated")

# ---- STAGE 2: WHITE NOISE ---------------------------------------------------
def _check_white() -> None:
    from satellite_parameters import ImuSimParameters
    # only white noise on: perfect but with finite gyro/mag noise
    _sun_white = replace(
        ImuSimParameters.perfect().sun_array, enable_white_noise=True,
        cells=tuple(replace(c, white_noise_sigma=0.003)
                    for c in ImuSimParameters.perfect().sun_array.cells))
    cfg0 = replace(ImuSimParameters.perfect(),
                   gyro_white_noise_sigma_rad_s=0.00052,
                   mag_white_noise_sigma_t=80e-9,
                   sun_array=_sun_white)
    imu = SimulatedIMU(cfg0)
    _synthetic_gyro_loop(imu, duration_s=600.0)
    ge = np.array([r["meas"] - r["truth"] for k, r in imu.records if k == "gyro"])
    me = np.array([r["meas"] - r["truth"] for k, r in imu.records if k == "mag"])
    tgt = cfg0.gyro_white_noise_sigma_rad_s
    ok_g = all(abs(ge[:, i].std() - tgt) < 0.25 * tgt for i in range(3))
    _check("WHITE", "6 gyro noise std", ok_g,
           f"std X/Y/Z = {np.degrees(ge[:, 0].std()):.4f}/{np.degrees(ge[:, 1].std()):.4f}/"
           f"{np.degrees(ge[:, 2].std()):.4f} deg/s (target 0.0298, +/-25%)")
    tm = cfg0.mag_white_noise_sigma_t
    ok_m = all(abs(me[:, i].std() - tm) < 0.25 * tm for i in range(3))
    _check("WHITE", "7 mag noise std", ok_m,
           f"std X/Y/Z = {me[:, 0].std()*1e9:.1f}/{me[:, 1].std()*1e9:.1f}/"
           f"{me[:, 2].std()*1e9:.1f} nT (target 80, +/-25%)")
    # (7b) sun ARRAY white noise: with everything else perfect and a constant
    # truth, the per-cell output scatter equals the configured fraction-of-
    # full-scale sigma (0.003 here), measured on a mid-scale cell.
    if imu._sun_array is not None:
        sa = imu._sun_array
        i = sa._names.index("+Z")
        outs = np.array([r["outputs"][i] for r in sa.records])
        sstd = float(outs.std())
        _check("WHITE", "7b sun cell noise", abs(sstd - 0.003) < 0.001,
               f"+Z output std = {sstd:.5f} (target 0.003, tol +/-0.001)")
    else:
        _check("WHITE", "7b sun cell noise", False, "no sun array owned")


# ---- STAGE 3: BIAS ----------------------------------------------------------
def _check_bias() -> None:
    from satellite_parameters import ImuSimParameters
    cfg0 = replace(ImuSimParameters.perfect(), gyro_bias_sigma_rad_s=0.005)
    imu = SimulatedIMU(cfg0)
    _synthetic_gyro_loop(imu, duration_s=600.0)
    ge = np.array([r["meas"] - r["truth"] for k, r in imu.records if k == "gyro"])
    means = ge.mean(axis=0)
    # a bias is a PERSISTENT offset: |mean| clearly nonzero on every axis
    # (white noise is zero here, so any persistent offset proves the bias)
    ok_load = all(abs(means[i]) > 0.0008 for i in range(3))
    widths = np.percentile(ge, [5, 95], axis=0)
    ok_small = np.all((widths[1] - widths[0]) < 0.001)  # very little spread
    _check("BIAS", "8 persistent offset", ok_load,
           f"mean error X/Y/Z = {np.degrees(means[0]):+.4f}/"
           f"{np.degrees(means[1]):+.4f}/{np.degrees(means[2]):+.4f} deg/s "
           f"all |.|>0.17 deg/s (drawn once, stays)")
    _check("BIAS", "9 not fresh noise", ok_small,
           f"90-10 error width < 0.057 deg/s on every axis (constant, not jumping)")


# ---- STAGE 4: WANDER --------------------------------------------------------
def _check_wander() -> None:
    from satellite_parameters import ImuSimParameters
    # wander only: fixed bias OFF, white OFF, wander large so it's measurable
    cfg0 = replace(ImuSimParameters.perfect(),
                   gyro_wander_sigma_rad_s=0.001, gyro_wander_tau_s=50.0)
    imu = SimulatedIMU(cfg0)
    _synthetic_gyro_loop(imu, duration_s=1000.0)
    ge = np.array([r["meas"] - r["truth"] for k, r in imu.records if k == "gyro"])
    if len(ge) < 300:
        _check("WANDER", "10 samples", False, "not enough samples")
        return
    mean_err = ge.mean(axis=0)
    # 1) the error CHANGES over time (wander) -- not a constant bias
    moving_std = ge[300:].std(axis=0)
    ok_changes = bool(np.all(moving_std > 0.0004))
    # 2) temporally CORRELATED: error at lag 1 s should stay similar
    x = ge[:, 0] - ge[:, 0].mean()
    var = float(np.mean(x * x))
    acf1 = float(np.mean(x[:-10] * x[10:]) / var)   # lag 1 s (10 samples)
    ok_corr = acf1 > 0.5
    _check("WANDER", "10 changes over time", ok_changes,
           f"error std across run = {moving_std[0]*1e3:.2f}/"
           f"{moving_std[1]*1e3:.2f}/{moving_std[2]*1e3:.2f} mrad/s (must be > 0.4)")
    _check("WANDER", "11 temporally correlated", ok_corr,
           f"lag-1 s autocorr = {acf1:.2f} (must be > 0.5 -- white noise would be ~0)")

# ---- STAGE 5: SCALE ---------------------------------------------------------
def _check_scale() -> None:
    from satellite_parameters import ImuSimParameters
    cfg0 = replace(ImuSimParameters.perfect(), gyro_scale_error=0.2,
                   mag_scale_error=0.2)
    imu = SimulatedIMU(cfg0)
    # truth along a single axis so the per-axis scale is directly measured
    _synthetic_gyro_loop(imu, duration_s=200.0, omega=np.array([1.0, 0.0, 0.0]))
    grecs = [r for k, r in imu.records if k == "gyro"]
    mrecs = [r for k, r in imu.records if k == "mag"]
    rx = np.array([r["meas"][0] / r["truth"][0] for r in grecs])
    ratio = float(np.median(rx))
    ok = 0.05 < abs(ratio - 1.0) < 0.7
    _check("SCALE", "12 gyro scale applied", ok,
           f"median meas/truth on X = {ratio:.3f} (0.2 scale draw, "
           f"so clearly off 1.0 and within [0.3, 0.95] or [1.05, 1.7])")
    # mag scale: truth B_body is a nice vector; meas/truth per the drawn scale
    mr = np.array([r["meas"] / r["truth"] for r in mrecs])
    med_m = np.median(mr, axis=0)
    ok_m = float(np.any(np.abs(med_m - 1.0) > 0.05))
    _check("SCALE", "13 mag scale applied", ok_m,
           f"median meas/truth per axis = {med_m[0]:.3f}/{med_m[1]:.3f}/{med_m[2]:.3f} "
           f"(at least one axis clearly off 1.0)")


# ---- STAGE 6: MISALIGNMENT --------------------------------------------------
def _check_misalignment() -> None:
    from satellite_parameters import ImuSimParameters
    cfg0 = replace(ImuSimParameters.perfect(), gyro_misalignment_rad=0.5,
                   mag_misalignment_rad=0.5)
    imu = SimulatedIMU(cfg0)
    # truth is a PURE Z spin / PURE Z field: any X/Y measured content proves
    # cross-axis coupling (misalignment), not scale (scale on Z only stretches Z).
    _synthetic_gyro_loop(imu, duration_s=100.0, omega=np.array([0.0, 0.0, 1.0]))
    grecs = [r for k, r in imu.records if k == "gyro"]
    mrecs = [r for k, r in imu.records if k == "mag"]
    gx = np.median([r["meas"][0] for r in grecs])   # X leak from pure Z truth
    gy = np.median([r["meas"][1] for r in grecs])
    gz = np.median([r["meas"][2] for r in grecs])
    ok_g = (abs(gx) > 0.05 or abs(gy) > 0.05) and 0.5 < gz < 1.5
    _check("MISALIGN", "14 gyro cross-coupling", ok_g,
           f"median meas with pure-Z truth = [{gx:+.3f}, {gy:+.3f}, {gz:+.3f}] rad/s "
           f"(X/Y leak proves M applied)")
    mx = np.median([r["meas"][0] for r in mrecs])
    my = np.median([r["meas"][1] for r in mrecs])
    _check("MISALIGN", "15 mag cross-coupling", abs(mx) > 1e-7 or abs(my) > 1e-7,
           f"median meas[T] = [{mx:.2e}, {my:.2e}, ...] with pure-Z body field "
           f"(X/Y content proves M_mag applied)")


# ---- STAGE 7: MAGNETOMETER BODY-FRAME CONVENTION ----------------------------
def _check_mag_frame() -> None:
    from satellite_parameters import ImuSimParameters
    imu = SimulatedIMU(ImuSimParameters.perfect())
    # Known rotation: q = [cos45, 0, 0, sin45] is +90 deg about Z. Feeding
    # B_eci = [B,0,0] through the repo's own C_bi formula gives
    # B_body = [0,+B,0] (checked numerically against _dcm_bi_from_q -- the
    # check below asserts the sensor reproduces that exact vector). The
    # important property: the measured body field equals
    # _dcm_bi_from_q(q).T @ B_eci to machine precision. A body<->ECI swap
    # (using C_bi instead of C_bi.T) would give a DIFFERENT vector and fail.
    B = 2.0e-5
    q = np.array([np.cos(np.pi / 4.0), 0.0, 0.0, np.sin(np.pi / 4.0)])
    imu.update(0.1, q, np.zeros(3), np.array([B, 0.0, 0.0]))
    mrecs = [r for k, r in imu.records if k == "mag" and r["valid"]]
    if not mrecs:
        _check("FRAME", "16 90deg body field", False, "no mag record")
        return
    meas = mrecs[0]["meas"]
    expect = _dcm_bi_from_q(q).T @ np.array([B, 0.0, 0.0])   # == [0, +B, 0]
    ok = float(np.linalg.norm(meas - expect)) < 1e-12 and abs(meas[1] - B) < 1e-12
    _check("FRAME", "16 90deg body field", ok,
           f"B_eci=[{B:.0e},0,0] @ +90deg-about-Z -> body = "
           f"[{meas[0]:+.2e}, {meas[1]:+.2e}, {meas[2]:+.2e}] T (expect [0, +{B:.0e}, 0])")
    # identity attitude: body field == ECI field (use zero latency so the
    # buffered truth is exactly this sample, no interpolation lag)
    imu2 = SimulatedIMU(replace(ImuSimParameters.perfect(), gyro_latency_mean_s=0.0,
                                gyro_latency_sigma_s=0.0, gyro_latency_min_s=0.0,
                                gyro_latency_max_s=0.0, mag_latency_mean_s=0.0,
                                mag_latency_sigma_s=0.0, mag_latency_min_s=0.0,
                                mag_latency_max_s=0.0))
    imu2.update(0.1, np.array([1.0, 0.0, 0.0, 0.0]), np.zeros(3),
                np.array([0.0, 1.0e-5, 0.5e-5]))
    m2 = [r for k, r in imu2.records if k == "mag" and r["valid"]][-1]["meas"]
    ok_id = float(np.linalg.norm(m2 - np.array([0.0, 1.0e-5, 0.5e-5]))) < 1e-12
    _check("FRAME", "17 identity body field", ok_id,
           f"id attitude -> body == ECI: max diff "
           f"{float(np.linalg.norm(m2 - np.array([0.0, 1e-5, 0.5e-5]))):.2e} T (< 1e-12)")

# ---- STAGE 8: SATURATION ------------------------------------------------------
def _check_saturation() -> None:
    from satellite_parameters import ImuSimParameters
    # tiny ranges so the normal synthetic truth (0.3 rad/s, ~2.7e-5 T field)
    # blows past them on every sample.
    cfg0 = replace(ImuSimParameters.perfect(), gyro_range_rad_s=0.05,
                   mag_range_t=1.0e-6)
    imu = SimulatedIMU(cfg0)
    _synthetic_gyro_loop(imu, duration_s=100.0)
    grecs = [r for k, r in imu.records if k == "gyro"]
    mrecs = [r for k, r in imu.records if k == "mag"]
    ok_g = (bool(grecs) and all(r["saturated"] for r in grecs)
            and all(float(np.max(np.abs(r["meas"]))) <= 0.05 + 1e-12 for r in grecs))
    _check("SAT", "18 gyro clipped+flagged", ok_g,
           f"{len(grecs)} samples, all saturated, "
           f"max |meas| = {max(float(np.max(np.abs(r['meas']))) for r in grecs):.4f} rad/s "
           f"(range 0.05)")
    ok_m = (bool(mrecs) and all(r["saturated"] for r in mrecs)
            and all(float(np.max(np.abs(r["meas"]))) <= 1.0e-6 + 1e-18 for r in mrecs))
    _check("SAT", "19 mag clipped+flagged", ok_m,
           f"{len(mrecs)} samples, all saturated, "
           f"max |meas| = {max(float(np.max(np.abs(r['meas']))) for r in mrecs):.2e} T "
           f"(range 1e-6)")


# ---- STAGE 9: DROPOUT ---------------------------------------------------------
def _check_dropout() -> None:
    from satellite_parameters import ImuSimParameters
    p = 0.05
    cfg0 = replace(ImuSimParameters.perfect(), gyro_dropout_probability=p,
                   mag_dropout_probability=p)
    imu = SimulatedIMU(cfg0)
    _synthetic_gyro_loop(imu, duration_s=600.0)   # 6000 samples per sensor
    grecs = [r for k, r in imu.records if k == "gyro"]
    mrecs = [r for k, r in imu.records if k == "mag"]
    fg = sum(1 for r in grecs if not r["valid"]) / max(len(grecs), 1)
    fm = sum(1 for r in mrecs if not r["valid"]) / max(len(mrecs), 1)
    ok_g = abs(fg - p) < 0.02
    _check("DROPOUT", "20 gyro dropout fraction", ok_g,
           f"measured {fg:.4f} vs configured {p:.2f} "
           f"({sum(1 for r in grecs if not r['valid'])}/{len(grecs)} dropped, tol +/-0.02)")
    ok_m = abs(fm - p) < 0.02
    _check("DROPOUT", "21 mag dropout fraction", ok_m,
           f"measured {fm:.4f} vs configured {p:.2f} "
           f"({sum(1 for r in mrecs if not r['valid'])}/{len(mrecs)} dropped, tol +/-0.02)")


# ---- STAGE 10: DETERMINISM ----------------------------------------------------
def _check_determinism() -> None:
    from satellite_parameters import ImuSimParameters
    cfg0 = ImuSimParameters.nominal()
    a = SimulatedIMU(cfg0)
    _synthetic_gyro_loop(a, duration_s=100.0)
    b = SimulatedIMU(cfg0)
    _synthetic_gyro_loop(b, duration_s=100.0)
    ga = np.array([r["meas"] for k, r in a.records if k == "gyro"])
    gb = np.array([r["meas"] for k, r in b.records if k == "gyro"])
    ma = np.array([r["meas"] for k, r in a.records if k == "mag"])
    mb = np.array([r["meas"] for k, r in b.records if k == "mag"])
    ok_same = (ga.shape == gb.shape and ma.shape == mb.shape
               and float(np.max(np.abs(ga - gb))) == 0.0
               and float(np.max(np.abs(ma - mb))) == 0.0)
    _check("DETERM", "22 same seed identical", ok_same,
           f"gyro max diff {float(np.max(np.abs(ga - gb))):.1e}, "
           f"mag max diff {float(np.max(np.abs(ma - mb))):.1e} (expect exactly 0)")
    cfg1 = replace(cfg0, seed=cfg0.seed + 1)
    c = SimulatedIMU(cfg1)
    _synthetic_gyro_loop(c, duration_s=100.0)
    gc = np.array([r["meas"] for k, r in c.records if k == "gyro"])
    ok_diff = float(np.max(np.abs(ga - gc))) > 0.0
    _check("DETERM", "23 different seed differs", ok_diff,
           f"gyro max diff vs seed+1 = {float(np.max(np.abs(ga - gc))):.3e} (expect > 0)")


# ---- RUNNER -------------------------------------------------------------------
def run_validation() -> int:
    """Run all 10 stages (25 checks). Prints a PASS/FAIL table, returns the
    process exit code (0 = all pass, 1 = any failure). Never weakens a
    tolerance to make it pass -- fix the code instead."""
    global _VAL_RESULTS
    _VAL_RESULTS = []
    print("=" * 78, flush=True)
    print(" SIMULATED IMU VALIDATION -- 10 stages, synthetic truth + real frame math",
          flush=True)
    print("=" * 78, flush=True)
    _check_perfect()
    _check_white()
    _check_bias()
    _check_wander()
    _check_scale()
    _check_misalignment()
    _check_mag_frame()
    _check_saturation()
    _check_dropout()
    _check_determinism()
    n_pass = sum(1 for _, _, ok, _ in _VAL_RESULTS if ok)
    n_fail = len(_VAL_RESULTS) - n_pass
    print("-" * 78, flush=True)
    print(f" RESULT: {n_pass} PASS, {n_fail} FAIL out of {len(_VAL_RESULTS)} checks",
          flush=True)
    for stage, name, ok, detail in _VAL_RESULTS:
        if not ok:
            print(f"   FAILED: [{stage}] {name}: {detail}", flush=True)
    return 0 if n_fail == 0 else 1


if __name__ == "__main__":
    if len(sys.argv) > 1 and sys.argv[1].lower().startswith("valid"):
        sys.exit(run_validation())
    run_demo()
